# Generated by Django 5.0.6 on 2024-06-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_created_chat_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='statement',
            field=models.CharField(choices=[('BU', 'Бизнес'), ('IN', 'Изобретения'), ('FA', 'Мода')], max_length=2),
        ),
    ]
